using System;
using System.Collections.Generic;
using System.Text;

namespace SAPBlazorAnimate.Models
{
    public enum AnimateType
    {
        /// <summary>
        /// bounce
        /// </summary>
        bounce,
        shake,
        wobble,
        bounceInLeft,
        bounceOutDown,
        fadeIn,
        fadeInLeftBig,
        fadeInUpBig,
        fadeOutLeft,
        fadeOutUp,
        flipOutX,
        rotateIn,
        rotateInUpRight,
        rotateOutUpLeft,
        rollIn,
        zoomInLeft,
        zoomOutDown,
        slideInDown,
        slideOutDown,
        heartBeat,
        flash,
        headShake,
        jello,
        bounceInRight,
        bounceOutLeft,
        fadeInDown,
        fadeInRight,
        fadeOut,
        fadeOutLeftBig,
        fadeOutUpBig,
        flipOutY,
        rotateInDownLeft,
        rotateOut,
        rotateOutUpRight,
        rollOut,
        zoomInRight,
        zoomOutLeft,
        slideInLeft,
        slideOutLeft,
        pulse,
        swing,
        bounceIn,
        bounceInUp,
        bounceOutRight,
        fadeInDownBig,
        fadeInRightBig,
        fadeOutDown,
        fadeOutRight,
        flipInX,
        lightSpeedIn,
        rotateInDownRight,
        rotateOutDownLeft,
        hinge,
        zoomIn,
        zoomInUp,
        zoomOutRight,
        slideInRight,
        slideOutRight,
        rubberBand,
        tada,
        bounceInDown,
        bounceOut,
        bounceOutUp,
        fadeInLeft,
        fadeInUp,
        fadeOutDownBig,
        fadeOutRightBig,
        flip,
        flipInY,
        lightSpeedOut,
        rotateInUpLeft,
        rotateOutDownRight,
        jackInTheBox,
        zoomInDown,
        zoomOut,
        zoomOutUp,
        slideInUp,
        slideOutUp

    }

}
